### PR TITLE
remove base_configurable

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
This is needed by https://github.com/mirage/mirage/pull/1047

**Comment by hannesm** [comment]
I'd prefer to have the mirage-skeleton master being buildable by the most recent released mirage, and keep the compatibility with mirage-master on a custom branch (i.e. `mirage-dev`). The reason is that anyone who wants to follow the installation instructions from our homepage will get working mirage-skeleton unikernels using the opam-installed mirage.

**Comment by samoht** [comment]
Hum yes, good point. I'll revert this and make a `mirage-dev` branch.

**Comment by hannesm** [comment]
thanks @samoht

**Pull request merged**
