### PR TITLE
Be able to define multiple overlays and add them when we compile mirage-skeleton

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by dinosaure** [comment]
I did mirage/mirage#1270 to homogenize shell environment,

**Comment by TheLortex** [comment]
In your PR the parsing expects a space-separated list, but in mirage it's a comma-separated list so for consistency it should also be comma-separated in this Makefile.

**Comment by dinosaure** [comment]
Yes, I will try to find how to converge that.

**Pull request merged**
