### PR TITLE
make README sample-* make commands more obvious

### LINKED ISSUE #131: Example from README: mirage: unknown option --unix
After installing mirage 2.7.3 from OPAM on a Debian X86, examples given in the README result in:

    :mirage-skeleton $ make sample-configure
    mirage configure -f sample/config.ml --unix 
    mirage: unknown option `--unix'.
    Usage: mirage configure [OPTION]... 
    Try `mirage configure --help' or `mirage --help' for more information.
    Makefile:41: recipe for target 'sample-configure' failed
    make: *** [sample-configure] Error 1

I also noticed that there is no file `sample/config.ml` file. Maybe sample refers to `hello` and so on but this isn't obvious. At this point I have no idea how to go on.

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #131, that I've also tapped into...

### CODE REVIEW

**Comment by srenatus** [comment]
Hmm looking into this, it doesn't seem like there were `*-run` targets defined currently:

```interactive
$ make hello-configure
mirage configure -f hello/config.ml --unix
# Detecting depexts using flags: x86_64 osx homebrew
# No extra OS packages requirements found.
[NOTE] Package functoria is already installed (current version is 1.1.0).
[NOTE] Package lwt is already installed (current version is 2.5.2).
[NOTE] Package mirage-clock-unix is already installed (current version is 1.0.0).
[NOTE] Package mirage-console is already installed (current version is 2.1.3).
[NOTE] Package mirage-logs is already installed (current version is 0.2).
[NOTE] Package mirage-types is already installed (current version is 2.8.0).
[NOTE] Package mirage-types-lwt is already installed (current version is 2.8.0).
[NOTE] Package mirage-unix is already installed (current version is 2.6.0).
$ make hello-build
mirage configure -f hello/config.ml --unix
# Detecting depexts using flags: x86_64 osx homebrew
# No extra OS packages requirements found.
[NOTE] Package functoria is already installed (current version is 1.1.0).
[NOTE] Package lwt is already installed (current version is 2.5.2).
[NOTE] Package mirage-clock-unix is already installed (current version is 1.0.0).
[NOTE] Package mirage-console is already installed (current version is 2.1.3).
[NOTE] Package mirage-logs is already installed (current version is 0.2).
[NOTE] Package mirage-types is already installed (current version is 2.8.0).
[NOTE] Package mirage-types-lwt is already installed (current version is 2.8.0).
[NOTE] Package mirage-unix is already installed (current version is 2.6.0).
cd hello && /Library/Developer/CommandLineTools/usr/bin/make
ocamlbuild -use-ocamlfind -pkgs functoria.runtime,mirage-clock-unix,mirage-console.unix,mirage-logs,mirage-types.lwt,mirage-unix,mirage.runtime -tags "th
read,warn(A-4-41-44),debug,bin_annot,strict_sequence,principal,safe_string" -tag-line "<static*.*>: warn(-32-34)" -cflag -g -lflags -g,-linkpkg main.nati
ve
Finished, 10 targets (4 cached) in 00:00:00.
ln -nfs _build/main.native mir-console
$ make hello-run
make: *** No rule to make target `hello-run'.  Stop.
```

Trying to do the obvious in https://github.com/mirage/mirage-skeleton/pull/141/commits/b8ba6bb9fb6fbc2812aaabba163c120ab75b9f42, but I'm not sure if this is correct or if it should try to figure out the correct `mir-*` to call.

**Comment by hannesm** [comment]
I like a0dd5a1, and wonder whether we should just drop the `make run` target (rather describe in the README to execute `${example}/main.native`

**Comment by mor1** [comment]
I would also drop the `make run` target (and any `-run` targets).
Better to update the README as @hannesm suggests.

**Comment by srenatus** [comment]
@mor1, @hannesm: ok, updated. LGTM?

**Comment by hannesm** [comment]
thanks. looks good. travis failure is some unrelated 4.03 ppx-type-conv problem (already reported [here](https://github.com/ocaml/opam-repository/issues/6839))

**Comment by mor1** [comment]
LGTM-- Thanks!

(While I note @djs55 comment on #131 and making command lines cut'n'pasteable, this is certainly an improvement.)

**Pull request merged**
