### PR TITLE
test on both 4.02 and 4.03

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
something is wrong while compiling lwt#tracing branch according to travis: `ocamlfind: Package 'wikidoc' not found` (https://travis-ci.org/mirage/mirage-skeleton/jobs/137059786) -- any idea @talex5?

**Comment by Drup** [comment]
@hannesm It's not a failure, ignore it.

**Comment by hannesm** [comment]
Oh, ic. the failure is nevertheless in `lwt.dev`(likely needs to be updated for 4.03?):
```
# Error: This expression has type (string * Parsetree.expression) list
# [...]
#        Type string is not compatible with type Asttypes.arg_label 
```

**Comment by talex5** [comment]
There's this branch: https://github.com/talex5/lwt/tree/tracing-4.03.0

I think there was some problem getting a version of Lwt that worked with 4.02 and 4.03 at the same time.

**Comment by hannesm** [comment]
cool.  according to opam, lwt 2.5.2 works on both 4.02 and 4.03... any chance you can rebase the tracing branch in mirage/lwt clone onto 2.5.2? thx!

**Comment by talex5** [comment]
Done.

**Comment by hannesm** [comment]
thx! and travis is happy, merging now! :)

**Pull request merged**
