### PR TITLE
run all executables on travis

### PR DESCRIPTION
**Pull request by azul**
Test the things we build actually run.

### CODE REVIEW

**Comment by hannesm** [comment]
we can see that the examples don't work from travis... @all: try `make testrun` yourself and fix issues :D thanks for this testing improvement!

**Comment by samoht** [comment]
That's great! incoming PRs to remove camlp4 dependencies to the examples as well..

**Comment by yomimono** [comment]
Hm, this patch appears to be trying to run `main.native` after building projects generated with `mirage configure --xen`.  Configuring with the Xen target won't produce a runnable `main.native` but rather a minimal Xen virtual machine.  We don't currently have a nice way to run Xen unikernels through Travis, as far as I know.

**Comment by samoht** [comment]
Interesting failure mode. I have no idea where this comes from :-)

```
cd tracing && make
make[1]: Entering directory `/home/travis/build/mirage/mirage-skeleton/tracing'
ocamlbuild -use-ocamlfind -pkgs functoria.runtime,lwt.syntax,mirage-clock-unix,mirage-console.unix,mirage-net-unix,mirage-profile.unix,mirage-types.lwt,mirage.runtime,sexplib,tcpip.arpv4,tcpip.ethif,tcpip.ipv4,tcpip.stack-direct,tcpip.tcp,tcpip.udp -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -tag-line "<static*.*>: -syntax(camlp4o)" -cflag -g -lflags -g,-linkpkg main.native
Finished, 10 targets (0 cached) in 00:00:00.
ln -nfs _build/main.native mir-example
make[1]: Leaving directory `/home/travis/build/mirage/mirage-skeleton/tracing'
sh ./testrun.sh console
hello
sh ./testrun.sh network
Fatal error: exception Failure("net11")
Raised at file "src/core/lwt.ml", line 901, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 194, characters 5-10
make: *** [network-testrun] Error 1
```

**Comment by samoht** [comment]
And yes, although it would be nice, we can't start VMs in Travis. I'm not even sure we can do fancy network stuff in there...

**Comment by avsm** [comment]
> And yes, although it would be nice, we can't start VMs in Travis. I'm not even sure we can do fancy network stuff in there...

You can run Docker containers in there now, although only socket and not hostnet

**Comment by azul** [comment]
Ahh.. I did not think about the xen versions. I was suspecting everything would also be build for unix. So running that one seemed better than nothing. Only other option that comes to my mind would be deploying the result somewhere.

**Comment by samoht** [comment]
@azul A possible solution is to replace `make MODE=unix && make clean` by `make MODE=unix && make run make clean` in  `.travis.yml`.

**Comment by azul** [comment]
@samoht rebased and remove testrun from xen build.

**Comment by azul** [comment]
Looks like running the network executable just failed due to permission issues. Using port 8080 and net=socket now.

**Comment by azul** [comment]
`net=socket` is problematic for examples that do not use the network interface at all. So instead we now run all examples as root. :fearful:

**Comment by hannesm** [comment]
this is a great source on how to find problems, atm it seems that console example (or test setup) is not well-behaving:
`Error: The files /home/travis/.opam/system/lib/mirage-console/console_unix.cmi and unikernel.cmi make inconsistent assumptions over interface Sexplib`

I'd be in favor of merging this soon, and fixing problems afterwards in separate PRs

**Comment by samoht** [comment]
agreed.

**Comment by hannesm** [comment]
(side note: I just rebased the mirage-dev branch on top of master)

**Pull request merged**
