### PR TITLE
Charrua 0.3

### PR DESCRIPTION
**Pull request by yomimono**
Make DHCP example compile against current charrua-core (0.3).

### CODE REVIEW

**Comment by hannesm** [comment]
rebase/cherry-picking 85d1e35 instead of merging master!?

**Comment by yomimono** [comment]
Tests are failing on trying to build the `tracing` example - it appears there might be a missing dependency:

```
cd tracing && make

make[1]: Entering directory `/home/travis/build/mirage/mirage-skeleton/tracing'

ocamlbuild -use-ocamlfind -pkgs functoria.runtime,mirage-clock-unix,mirage-console.unix,mirage-net-unix,mirage-profile.unix,mirage-types.lwt,mirage-unix,mirage.runtime,tcpip.arpv4,tcpip.ethif,tcpip.ipv4,tcpip.stack-direct,tcpip.tcp,tcpip.udp -tags "warn(A-4-41-44),debug,bin_annot,strict_sequence,principal,safe_string" -tag-line "<static*.*>: warn(-32-34)" -cflag -g -lflags -g,-linkpkg main.native

+ ocamlfind ocamlopt -g -linkpkg -linkpkg -g -package tcpip.udp -package tcpip.tcp -package tcpip.stack-direct -package tcpip.ipv4 -package tcpip.ethif -package tcpip.arpv4 -package mirage.runtime -package mirage-unix -package mirage-types.lwt -package mirage-profile.unix -package mirage-net-unix -package mirage-console.unix -package mirage-clock-unix -package functoria.runtime key_gen.cmx unikernel.cmx main.cmx -o main.native

/home/travis/.opam/system/lib/mirage-profile/libmProf_unix_stubs.a(time_stubs.o): In function `stub_mprof_get_monotonic_time':

/home/travis/.opam/system/build/mirage-profile.0.7.0/_build/unix/time_stubs.c:31: undefined reference to `clock_gettime'

collect2: ld returned 1 exit status

File "caml_startup", line 1:

Error: Error during linking

Command exited with code 2.

Hint: Recursive traversal of subdirectories was not enabled for this build,

  as the working directory does not look like an ocamlbuild project (no

  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,

  you should add the option "-r" or create an empty '_tags' file.

  

  To enable recursive traversal for some subdirectories only, you can use the

  following '_tags' file:

  

      true: -traverse

      <dir1> or <dir2>: traverse

      

Compilation unsuccessful after building 10 targets (0 cached) in 00:00:00.

make[1]: *** [main.native] Error 10

make[1]: Leaving directory `/home/travis/build/mirage/mirage-skeleton/tracing'

make: *** [tracing-build] Error 2

'unset TESTS; OPAMYES=1 export OPAMYES; set -ue; make MODE=unix && make testrun SUDO=sudo && make clean' exited 2. Terminating with 2
```

@talex5, is it possible that something's missing for mirage-profile 0.7.0?

**Comment by talex5** [comment]
It's linking with `mirage-profile.unix` (good), which should pull in `-lrt` e.g.

```
~/.opam/4.02.3/lib/mirage-profile$ ocamlobjinfo mProf_unix.cma |grep object
Extra C object files: -lrt -lrt -lmProf_unix_stubs
```

**Comment by yomimono** [comment]
I'm going to merge this PR and open a separate issue for the `tracing` test failure.

**Pull request merged**
