### PR TITLE
Update to latest mirage

### PR DESCRIPTION
**Pull request by samoht**
To be tested with https://github.com/mirage/mirage/pull/1442

### CODE REVIEW

**Comment by hannesm** [comment]
that looks nice, but would you mind to separate the ocamlformat changes (whitespaces, new lines) from the actual changes?

**Comment by samoht** [comment]
Rebased on top of #365 - see https://github.com/mirage/mirage-skeleton/pull/364/commits/40231d04e7721d021766fe42e4a6858b9de04a4f for the related changes.

**Comment by hannesm** [comment]
Unfortunately this broke mirage-skeleton on main branch with the latest released mirage tool.

It seems like we're still lacking documentation thereof (and I've no clue how the CI system is configured / working), but I'd really like to have:
- `main` branch of mirage-skeleton works with latest opam-released mirage
- `dev` branch of mirage-skeleton works with main branch of mirage

this allows people passing by to just use mirage & mirage-skeleton as documented. It would be great to have https://github.com/mirage/mirage/issues/1381 / #338 in place very soon to get nice error messages to the users instead of confusing them with errors such as:

```
(hello-key unikernel)
776.935s:# File "unikernel.ml", line 7, characters 2-20:
776.935s:# 7 |   Mirage_runtime.key key
776.935s:#       ^^^^^^^^^^^^^^^^^^
776.935s:# Error: Unbound value Mirage_runtime.key
```

```
(static-website-tls)
581.409s:+ mirage configure -t hvt --http 80 --https 443 '--allocation-policy=best-fit' --context ./mirage/context --no-extra-repo
582.639s:mirage: unknown option '--http', did you mean '--help'?
582.639s:        unknown option '--https'.
582.639s:Usage: mirage configure [OPTION]…
582.639s:Try 'mirage configure --help' or 'mirage --help' for more information.
```

what do you think?

**Comment by hannesm** [comment]
^^ @samoht. In a nice world, the mirage-CI would actually enforce this -- so testing pushes/PRs to the main branch with the released mirage, while testing pushes/PRs to the dev branch with mirage pinned to its main branch. and also, testing PRs to mirage with the dev branch of mirage-skeleton (+to test with PR comment thingy).

**Comment by samoht** [comment]
woops, I should have opened this PR against dev. Let me try to fix this...

And yes your scheme makes sense (and corresponds to my understanding of our current worfklows) but the current CI doesn't test this: https://github.com/ocurrent/mirage-ci/blob/main/src/pipelines/PR.ml#L585-L589. Let me try to fix this (bis).

**Comment by samoht** [comment]
I've reverted this PR: #375

**Comment by hannesm** [comment]
see https://github.com/ocurrent/mirage-ci/pull/37 which may do the thing we're interested in!?

**Pull request merged**
