### PR TITLE
Rename mirage-http to cohttp-mirage

### PR DESCRIPTION
**Pull request by djs55**
Related to [mirage/ocaml-cohttp#572]

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
Unfortunately the PIN for `cohttp-mirage` blocks asking the user whether they want to define the package or not (since it doesn't exist yet in the opam-repository). I think I'll add something to `mirage/opam-repo-dev`

**Comment by hannesm** [comment]
@djs55 while I appreciate fixing for new package releases, I'm against that people merge their own PRs in this organisation (unless approved by someone else).

In this case, I still have in mind that the master branch of mirage-skeleton is supposed to work with packages released to the main opam repository (which is now no longer the case - cohttp-mirage is missing there, the mirage tool needs to be pinned as well) - whereas a dev branch in here should work with mirage-dev remote (that's where lock-step releases should be gathered).  The reasoning behind this is that newcomers should have a pleasant experience when working on the tutorial - I'm aware that our state with OCaml 4.06.0 is not very good right now, but this PR made the experience using any other OCaml compiler bad as well.

**Comment by djs55** [comment]
Sorry for any disruption caused -- I'm trying to complete the `cohttp` release to fix the `-safe-string` problem which has become urgent since the 4.06.0 release. Shall I move this branch to `mirage-dev` and restore `master` to the previous state in the meantime?

**Comment by djs55** [comment]
To minimise disruption I've reverted `master` and pushed the changes to `mirage-dev` instead. I wonder if we could document the policy somewhere in this repo -- perhaps in a `CONTRIBUTING.md`?

I've also made
- [mirage/ocaml-cohttp#585] to release `ocaml-cohttp` and `cohttp-mirage`. This includes the module renaming but is urgent because it also includes the OCaml 4.06 `-safe-string` fix.
- [mirage/mirage#864] to update the `mirage` tool following the `cohttp-mirage` module rename.

**Comment by hannesm** [comment]
@djs55 thanks (both for your 4.06 safe-string work, and for reverting the master branch here to something which works with packages from opam-repository)!  The information used to be part of README.md (which used to be different (pointing to mirage-dev repo) in the mirage-dev branch).  I agree that we should revive this information either in README or create a CONTRIBUTING file.

**Pull request merged**
