### PR TITLE
include examples missed in Makefile

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
hmm, anybody an idea how to get two `netif` on Unix (code is using `netif "1"` and `netif "2"` in `config.ml`)?  Travis failure:

```
sudo sh ./testrun.sh netif-forward
Netif: plugging into 1 with mac 3a:b9:a2:45:fd:6b
Netif: connect 1
Fatal error: exception (Failure net12)
Raised at file "src/core/lwt.ml", line 901, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 95, characters 5-10
make: *** [netif-forward-testrun] Error 1
'unset TESTS; OPAMYES=1 export OPAMYES; set -ue; make MODE=unix && make testrun SUDO=sudo && make clean' exited 2. Terminating with 2
```

**Comment by yomimono** [comment]
I can reproduce this locally; hacking up `main.ml` to output the underlying error from `netif` gives the following:

```
$ sudo ./mir-network
Netif: plugging into 1 with mac 6a:88:ac:db:da:68
Netif: connect 1
undiagnosed error - (Failure "tun[TUNSETIFF]: Device or resource busy")Fatal error: exception (Failure net12)
Raised at file "src/core/lwt.ml", line 789, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 97, characters 5-10
```

`mirage-net-unix` does pass the (supposedly unique) device name through to tuntap when initializing the interface.

**Comment by mor1** [comment]
Think @koleini had done this. But what you've done looks right as far as I
recall it... :/

On 28 June 2016 at 12:57, Hannes Mehnert <notifications@github.com> wrote:

> hmm, anybody an idea how to get two netif on Unix (code is using netif "1"
> and netif "2" in config.ml)? Travis failure:
>
> sudo sh ./testrun.sh netif-forward
> Netif: plugging into 1 with mac 3a:b9:a2:45:fd:6b
> Netif: connect 1
> Fatal error: exception (Failure net12)
> Raised at file "src/core/lwt.ml", line 901, characters 22-23
> Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
> Called from file "main.ml", line 95, characters 5-10
> make: *** [netif-forward-testrun] Error 1
> 'unset TESTS; OPAMYES=1 export OPAMYES; set -ue; make MODE=unix && make testrun SUDO=sudo && make clean' exited 2. Terminating with 2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mirage/mirage-skeleton/pull/142#issuecomment-229028148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKP4AGJf9DUDovb_aqOGU4XN9FkOyCtks5qQQwsgaJpZM4I_jBh>
> .
>



-- 
Richard Mortier
mort@cantab.net

**Comment by koleini** [comment]
@hannesm can you try it again using```tap0``` and tap1``` for ```netif``` instead of numeric names?

**Comment by yomimono** [comment]
The generated `main.ml` looks like it'll try to use the same network twice:

```
let net11 = lazy (
  Netif.connect (Key_gen.network ())
  )

let net12 = lazy (
  Netif.connect (Key_gen.network ())
  )
```

ISTR a particular invocation being required to get the two-interface case working in functoria; I'm trying to dig it up.

**Comment by yomimono** [comment]
Aha, apparently some rando filed an issue about this back in January: https://github.com/mirage/mirage/issues/481

**Comment by hannesm** [comment]
ah, great. I cherry-picked your commit from #143 onto here (since #143 won't built due to `lwt.syntax`)!

**Comment by hannesm** [comment]
IMHO good to merge -- the 4.03 trouble is addressed in opam-repository (that one? https://github.com/ocaml/opam-repository/pull/6854); and thx to @yomimono fixes the mirage/mirage#481 issue :)

**Comment by mor1** [comment]
LGTM!

**Pull request merged**
