### PR TITLE
Add a tracing example.

### PR DESCRIPTION
**Pull request by Drup**
This adds a tracing example, based on @talex5's [blog post](https://mirage.io/wiki/profiling).
On top of the documentation value, it also stresses the tracing code for mirage/functoria's CI.

### CODE REVIEW

**Comment by talex5** [comment]
Good idea. Can we get Travis to test it? It'll need a separate build environment with the tracing Lwt in `PINS`.

(Sending a `!` to port 7000 on a fixed IP is a slightly strange example. The wiki just used that because there happened to be a bug in the ARP code at that time that was a useful example. Maybe just running console's hello world example would be better?)

**Comment by Drup** [comment]
I just pushed a commit to enable it in CI. Feel free to modify the example here and in the wiki. :)

**Comment by Drup** [comment]
@talex5 hum, do you know what the CI error is ?

**Comment by talex5** [comment]
Could you try pinning `https://github.com/mirage/mirage-profile.git#v0.6`? I think it's just a missing linker flag that older systems need. Will publish a new opam release if it works now.

**Comment by Drup** [comment]
@talex5 done.

**Pull request merged**
