### PR TITLE
static_website: set Content-Type using magic-mime.

### PR DESCRIPTION
**Pull request by lnmx**
Discussion: http://lists.xenproject.org/archives/html/mirageos-devel/2015-05/msg00206.html

### CODE REVIEW

**Comment by dsheets** [comment]
LGTM. Thanks for fixing this! I'm tracking down the dependency bug that's causing the Xen build to fail.

**Comment by samoht** [comment]
It's because you need https://github.com/mirage/ocaml-conduit/pull/70

**Comment by dsheets** [comment]
Should we add the mirage-dev as an extra remote?

**Comment by samoht** [comment]
need to first release in mirage-dev mirage, conduit and mirage-http. I'm doing that now.

**Comment by samoht** [comment]
Can you rebase with master please? Thanks!

**Comment by lnmx** [comment]
I messed up the rebase earlier, but it should be OK now.

**Comment by samoht** [comment]
I've rerun the failing test

**Comment by samoht** [comment]
This code should definitely move to a shared library at one point (probably `mirage-http`) instead of being duplicated everywhere.

**Pull request merged**
