### PR TITLE
Remove "console" example, which duplicates "hello"

### LINKED ISSUE #210: "hello" and "console" are redundant
We don't need both of these.

### PR DESCRIPTION
**Pull request by yomimono**
Fixes #210 . PR to update the `hello-world.md` file in mirage-dev branch of mirage-www accordingly is at https://github.com/mirage/mirage-www/pull/507 .

### CODE REVIEW

**Comment by Drup** [comment]
@yomimono You don't want a very simple unikernel without keys ?

**Comment by yomimono** [comment]
I admit to not having much perspective anymore on whether the presence of keys complicates the tutorial too much.

I think what I actually want is a much small set of useful teaching examples, each of which has extensive prose written about it, and then a larger set of build-test unikernels.

**Comment by yomimono** [comment]
Having thought about it a bit more, I think I *would* like a very simple `noop` unikernel that not only has no keys, but also has no impls and therefore isn't functorized over anything.  Such a program is obviously not very useful but might be better for explaining only the how-it-builds pieces of invoking `mirage` (including what *isn't* linked when we build that way, like `Unix`).

**Comment by mor1** [comment]
I think keys are more complicated than not-keys :)
Strongly agree with your last comment, hence #215 (assuming I understood you correctly!)

**Pull request closed without merging**
