### PR TITLE
Fixes to compile with latest conduit+tls

### PR DESCRIPTION
**Pull request by samoht**
@hannesm or @pqwy is there a way to create a dumb `Tls.Config.server` value to check that the example works? Currently (with `Tls.Config.server ()`) I get:

```
Fatal error: exception Invalid_argument("Tls.Config: invalid configuration: certificate type or usage does not match")
```

on start-up.

### CODE REVIEW

**Comment by samoht** [comment]
I also need to add some client-side example to check that everything is fine.

**Comment by hannesm** [comment]
There is currently not, but soon (in the next X.509 release) there will be (`soon` means once PR 54 in X.509 is merged) -- which produces a fresh self-signed certificate:
````
let cert, priv = 
  let key = Nocrypto.Rsa.generate 1024 in
  let req = X509.CA.generate "localhost" (* soon: [`CN "localhost"] *) (`RSA key) in
  let t = X509.CA.sign req (`RSA key) "localhost" (* soon: [`CN "localhost"] *) in
  (t, key)
````

**Comment by samoht** [comment]
I've merged everything, create all the new packages in `mirage-dev` so now I'm re-running this PR to check that everything compiles. This process is painful ... @AltGr for christmas present I would like a way to transform a set of pinned packages into a grouped released in a repository of my choice :p

**Comment by samoht** [comment]
I have some patches to fix the vchan code under 4.01 (works fine with 4.02). Will push shortly.

**Comment by AltGr** [comment]
@samoht you mean something like a bulk `opam-publish` ?

**Comment by avsm** [comment]
@AltGr yeah -- the workflow is that we queue stable releases in a remote, and then want to splice them together as a single release.  Similar model to JS Core releases. Having an opam publish that could 'splice' a list of versioned packages between remotes would be v useful.

**Comment by samoht** [comment]
More than that, it would be useful to get a list of pinned package, run an `make release` on each and then bulk publish the results somewhere.

A good start would be to add a `build-release:` field in the opam file.

**Comment by samoht** [comment]
I've re-run the tests again, with patched `mirage` and `ocaml-conduit`.

**Pull request merged**
