### PR TITLE
Bring dhcp up to date, new configuration scheme.

### PR DESCRIPTION
**Pull request by haesbaert**
No need to use a dhcpd.conf style file anymore, dhcp_config.ml should be much
more flexible while not being so much harder to configure.

This saves me from updating the parser for all the "200 and something" dhcp
options and removes the KV_RO requirement from dhcp.

This is a compilation of the changes from haesbaert/mirage-skeleton:master, since it
diverged a little, in the future I'll work on mirage/mirage-skeleton.

Solves issue #136

### CODE REVIEW

**Comment by samoht** [comment]
That's great!

**Comment by yomimono** [comment]
This is an excellent improvement!  Thanks for including so many helpful examples in the `dhcp_config.ml`. :)

**Comment by mor1** [comment]
Agree! It would be nice to also remove use of `CONSOLE` at the same time if possible. But that's easy enough to do in a subsequent PR if not convenient now :)

**Comment by haesbaert** [comment]
hooray \o/

**Pull request merged**
