### PR TITLE
update mirage-dev

### PR DESCRIPTION
**Pull request by yomimono**
Pull in recent changes merged to master.

### CODE REVIEW

**Comment by hannesm** [comment]
I'd prefer to rebase the mirage-dev changes on top of master (and force-push this rebasement) to keep the history in a manageable way...

**Comment by yomimono** [comment]
I chose to do it through a PR to make sure I hadn't broken CI; do you know of a way that both results in a new CI run and doesn't create a merge commit?

**Comment by hannesm** [comment]
rebase, rename branch to XXX, push branch XXX, wait for CI, force-push as mirage-dev?

**Comment by yomimono** [comment]
Ah, sensible.  I'll do that in the future.

**Comment by talex5** [comment]
@hannesm What's the problem with a merge for keeping the history manageable?

**Comment by hannesm** [comment]
@talex5 isn't the question what the purpose is here?

for me, master should work with the stuff released in opam-repository.  mirage-dev with the mirage-dev repository.  once a new set of mirage libraries is released, mirage-dev needs to be merged into master.

clearly, you can just have trillions of merge commits in both branches, which all may fix something, but IMHO a straight history, where mirage-dev is just some commits ahead of master is much easier to handle and comprehend.

but maybe I'm just missing the right choice of tools.  I avoid merge commits.

see e.g. the overview of the branches at https://github.com/mirage/mirage-skeleton/branches -- it would IMHO be better to see that mirage-dev is n commits ahead of master, and not any behind master.

**Pull request merged**
