### PR TITLE
fix builds and make travis happy

### PR DESCRIPTION
**Pull request by hannesm**
(mainly to look whether travis is happy with the rest)

### CODE REVIEW

**Comment by hannesm** [comment]
this fails due to `static_website` pulls in cohttp, which depends on ppx_fields_conv, and for some reason 113.09.00 is chosen, not the current 113.33.

thus, sexplib is downgraded, and inconsistent sexplib is used... since it is tested using 4.02.3, I've no clue why this fails (the compilation succeeds for xen btw) any ideas?

**Comment by hannesm** [comment]
ah, mirage-http has a conflict upon newer sexplibs -- unneccessary because it does not even use sexplib.syntax... let me fix this in opam-repo

**Comment by hannesm** [comment]
another culprit (for downgrading of sexplib) is vchan https://github.com/mirage/ocaml-vchan/pull/78 is a PR, can someone merge and prepare a release, please?

**Comment by talex5** [comment]
I guess it's related to http://stackoverflow.com/questions/17150075/undefined-reference-to-clock-gettime-although-lrt-is-given (which is also on Ubuntu 12.04).

I don't understand why we're getting it, though. We're clearly passing `-lrt` to the link line that fails:

```
root@309f4d17dcab:/mnt/tracing/_build# ocamlfind ocamlopt -verbose -g -linkpkg -linkpkg -g -package tcpip.udp -package tcpip.tcp -package tcpip.stack-direct -package tcpip.ipv4 -package tcpip.icmpv4 -package tcpip.ethif -package tcpip.arpv4 -package mirage.runtime -package mirage-unix -package mirage-types.lwt -package mirage-profile.unix -package mirage-net-unix -package mirage-console.unix -package mirage-clock-unix -package functoria.runtime key_gen.cmx unikernel.cmx main.cmx -o main.native
[...]
+ gcc -o 'main.native'   '-L/root/.opam/system/lib/bytes' '-L/root/.opam/system/lib/ocplib-endian' '-L/root/.opam/system/lib/sexplib' '-L/root/.opam/system/lib/ipaddr' '-L/root/.opam/system/lib/result' '-L/root/.opam/system/lib/tcpip' '-L/root/.opam/system/lib/cmdliner' '-L/root/.opam/system/lib/fmt' '-L/root/.opam/system/lib/functoria' '-L/root/.opam/system/lib/astring' '-L/root/.opam/system/lib/mirage' '-L/root/.opam/system/lib/lwt' '-L/root/.opam/system/lib/io-page' '-L/root/.opam/system/lib/mirage-clock-unix' '-L/root/.opam/system/lib/mirage-unix' '-L/root/.opam/system/lib/mirage-types' '-L/root/.opam/system/lib/mirage-profile' '-L/root/.opam/system/lib/cstruct' '-L/root/.opam/system/lib/tuntap' '-L/root/.opam/system/lib/mirage-net-unix' '-L/root/.opam/system/lib/mirage-console' '-L/usr/lib/ocaml'  '/tmp/camlstartup14269f.o' '/usr/lib/ocaml/std_exit.o' 'main.o' 'unikernel.o' 'key_gen.o' '/root/.opam/system/lib/mirage-console/mirage_console_unix.a' '/root/.opam/system/lib/mirage-console/mirage-console.a' '/root/.opam/system/lib/mirage-net-unix/mirage-net-unix.a' '/root/.opam/system/lib/tuntap/tuntap.a' '/root/.opam/system/lib/cstruct/lwt_cstruct.a' '/root/.opam/system/lib/mirage-profile/mProf_unix.a' '/root/.opam/system/lib/mirage-unix/OS.a' '/root/.opam/system/lib/mirage-clock-unix/mirage-clock.a' '/root/.opam/system/lib/io-page/io_page_unix.a' '/root/.opam/system/lib/lwt/lwt-unix.a' '/root/.opam/system/lib/lwt/lwt-log.a' '/root/.opam/system/lib/mirage/mirage-runtime.a' '/root/.opam/system/lib/astring/astring.a' '/root/.opam/system/lib/functoria/functoria-runtime.a' '/root/.opam/system/lib/fmt/fmt.a' '/root/.opam/system/lib/cmdliner/cmdliner.a' '/root/.opam/system/lib/tcpip/tcpip-stack-direct.a' '/root/.opam/system/lib/tcpip/dhcpv4.a' '/root/.opam/system/lib/tcpip/icmpv4.a' '/root/.opam/system/lib/result/result.a' '/root/.opam/system/lib/tcpip/arpv4.a' '/root/.opam/system/lib/tcpip/ethif.a' '/root/.opam/system/lib/tcpip/tcp.a' '/root/.opam/system/lib/tcpip/ipv6.a' '/root/.opam/system/lib/tcpip/ipv4.a' '/root/.opam/system/lib/tcpip/udp.a' '/root/.opam/system/lib/tcpip/tcpip.a' '/root/.opam/system/lib/mirage-profile/mProf.a' '/root/.opam/system/lib/lwt/lwt.a' '/root/.opam/system/lib/lwt/lwt-tracing.a' '/root/.opam/system/lib/ipaddr/ipaddr.a' '/root/.opam/system/lib/io-page/io_page.a' '/root/.opam/system/lib/cstruct/cstruct.a' '/root/.opam/system/lib/sexplib/sexplib.a' '/root/.opam/system/lib/ocplib-endian/bigstring.a' '/root/.opam/system/lib/ocplib-endian/ocplib_endian.a' '/usr/lib/ocaml/bigarray.a' '/usr/lib/ocaml/unix.a' '/usr/lib/ocaml/stdlib.a' '-ltuntap_stubs' '-lrt'
  '-lrt' '-lmProf_unix_stubs' '-lio_page_unix_stubs' '-llwt-unix_stubs' '-L/usr/lib' '-lpthread' '-ltcpip_stubs' '-lcstruct_stubs' '-lbigarray' '-lunix' '/usr/lib/ocaml/libasmrun.a' -lm  -ldl
/root/.opam/system/lib/mirage-profile/libmProf_unix_stubs.a(time_stubs.o): In function `stub_mprof_get_monotonic_time':
/root/.opam/system/build/mirage-profile.0.7.0/_build/unix/time_stubs.c:31: undefined reference to `clock_gettime'
```

And `-lmProf_unix_stubs` wants `clock_gettime`:

```
root@309f4d17dcab:/mnt/tracing/_build# nm /root/.opam/system/lib/mirage-profile/libmProf_unix_stubs.a 

time_stubs.o:
                 U _GLOBAL_OFFSET_TABLE_
                 U caml_array_bound_error
                 U clock_gettime
0000000000000000 T stub_mprof_get_monotonic_time
```

**Comment by talex5** [comment]
Could you try with this pin:

    opam pin add mirage-profile "https://github.com/talex5/mirage-profile.git#fix-u1204"

**Comment by hannesm** [comment]
ok. thanks @talex5, this works.

changes in here:
- don't run it twice (there's no build-test in opam, but a post_install_hook which does testing)
- in Makefile: don't have %-testrun depend on %-build, otherwise it is built again during testrun (someone with higher Makefile magic skills might want to embed advanced dependency tracking in here, such as if `main.ml` exists, no `mirage --configure` needed; if `main.native` exists, no need for building)
- `block` has a custom build step which also generates the `disk.img` needed for execution (I believe this can be done better using some functoria magic these days, but I don't know those spells)
- fix tracing example (patch by @talex5)

--> please look through and merge (@talex5 @samoht @yomimono) -- this makes travis green again :)

**Comment by hannesm** [comment]
(since talex5 merged fix into mirage-profile, I updated the PIN to point to mirage/mirage-profile on master)

**Comment by hannesm** [comment]
anyone against this PR? @mor1 @avsm (the top two contributors to this repo)?

**Comment by mor1** [comment]
LGTM. Merged. Thanks!

**Comment by hannesm** [comment]
thanks!

**Comment by hannesm** [comment]
(I rebased `mirage-dev` on top of this and force-pushed)

**Pull request merged**
